<?php

/**
 * @file
 * Contains views_delete_duplicate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Implements hook_help().
 */
function views_delete_duplicate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the views_delete_duplicate module.
    case 'help.page.views_delete_duplicate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provide the function to delete druplicates from views based on content id.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_query_alter().
 */
function views_delete_duplicate_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $views = [
    'taxonomy_term'      => 'block_2', 
    '_carouselnotizie_i' => 'block_1',
  ];

  foreach($views as $name => $block) { 
    if($view->id() == $name && $view->getDisplay()->view->current_display == $block) {
      $query->addField(NULL, 'node_field_data.nid', '', ['function' => 'groupby']);
      $query->addGroupBy('node_field_data.nid');
    }
  }
}
