#
# Travis CI
#
language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - ~/.composer

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --ignore-platform-reqs

script:
  - composer ci
  - composer validate

branches:
  only:
    - 8.x-2.x
